services:
  
  db:
    image: postgres:16-alpine
    container_name: aifixr
    environment:
      - POSTGRES_DB=aifixrdb
      - POSTGRES_USER=aifixr
      - POSTGRES_PASSWORD=Aifixr0930!
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-cloud
  
  eureka-server:
    build:
      context: .
      dockerfile: ./server/eureka/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-cloud

  config-server:
    build:
      context: .
      dockerfile: ./server/config/Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      - SERVER_PORT=8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - spring-cloud

  discovery-server:
    build:
      context: .
      dockerfile: ./server/discovery/Dockerfile
    container_name: discovery-server
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - spring-cloud

  common-service:
    build:
      context: .
      dockerfile: ./service/common/Dockerfile
    container_name: common-service
    ports:
      - "8101:8080"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - spring-cloud

  environment-service:
    build:
      context: .
      dockerfile: ./service/environment/Dockerfile
    container_name: environment-service
    ports:
      - "8084:8080"
    depends_on:
      - discovery-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - spring-cloud

  soccer-service:
    build:
      context: .
      dockerfile: ./service/soccer/Dockerfile
    container_name: soccer-service
    ports:
      - "8085:8080"
    depends_on:
      - db
      - eureka-server
      - discovery-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/aifixrdb
    networks:
      - spring-cloud

  user-service:
    build:
      context: .
      dockerfile: ./service/user/Dockerfile
    container_name: user-service
    ports:
      - "8086:8080"
    depends_on:
      - discovery-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS=-Deureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - spring-cloud

  ui-server:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: ui-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    restart: unless-stopped
    networks:
      - spring-cloud

  

networks:
  spring-cloud:
    driver: bridge

volumes:
  postgres-data:

