spring:
  application:
    name: soccer
  cloud:
    compatibility-verifier:
      enabled: false
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
  datasource:
    url: jdbc:postgresql://db:5432/aifixrdb
    username: aifixr
    password: Aifixr0930!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
